service:
  golangci-lint-version: 1.52.2
run:
  deadline: 30m
  skip-dirs:
    - cover
    - fix42
    - fix44
  modules-download-mode: readonly

#--timeout=10m --skip-dirs=fix42,fix44 --exclude="Error return value of .(store.cache.*|suite.msgStore.*). is not checke"

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - errcheck
      text: " is not checke"

linters:
  enable:
    - exportloopref
    - goimports
  disable:
    - structcheck
