name: sprint pre-merge check

on: 
  push:
    branches:
    - master
    - develop
    - features/sprint*
    - ci
    paths-ignore:
    - '.github/workflows/golangci-lint.yaml'
    - 'README.md'
  pull_request:
    branches:
    - master
    - develop
    - features/sprint*

jobs:
  build-and-test:
    name: build & test
    timeout-minutes: 20
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x]

    steps:
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
    - name: go-mod
      run: go mod download
    - name: go-build
      run: make build
    - name: go_test
      run: go test
    - name: go_vet
      run: make

  fix-protocol-test:
    name: protocol test
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        fix-version: [fix40, fix41, fix42, fix43, fix44, fix50, fix50sp1, fix50sp2]

    steps:
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - uses: actions/checkout@v2
    - name: go-mod
      run: go mod download
    - name: go-build
      run: make build_accept
    - name: fix_test
      env:
        fix_version: ${{ matrix.fix-version }}
      run: make $fix_version
